package org.ecs160.a2;

import static com.codename1.ui.CN.*;

import com.codename1.ui.*;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;

import org.ecs160.a2.ui.TaskEditor;

import org.ecs160.a2.ui.Summary;
import org.ecs160.a2.ui.TaskList;
import org.ecs160.a2.utils.Database;

import java.io.IOException;
import java.lang.Object;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class AppMain {

   private Form current;
   private Resources theme;
   public static TaskList taskList;
   private Toolbar toolbar;
   private Toolbar taskListToolbar;
   private Toolbar summaryToolbar;

   public void init(Object context) {
      // use two network threads instead of one
      updateNetworkThreadCount(2);

      theme = UIManager.initFirstTheme("/theme");

      // Enable Toolbar on all Forms by default
      Toolbar.setGlobalToolbar(true);

      // Pro only feature
      Log.bindCrashProtection(true);

      addNetworkErrorListener(err -> {
         // prevent the event from propagating
         err.consume();
         if (err.getError() != null) {
            Log.e(err.getError());
         }
         Log.sendLogAsync();
         Dialog.show("Connection Error",
                 "There was a networking error in the connection to " +
                         err.getConnectionRequest().getUrl(), "OK",
                 null);
      });

      Database.init();
   }

   public void start() {
      if (current != null) {
         current.show();
         return;
      }

      current = new Form("Task Management App", new BorderLayout());


      this.summaryToolbar = setToolbar();
      this.taskListToolbar = setToolbar();
      //setToolbar();
      setBottomTabs();

      TaskList.addSearch();

      current.setToolbar(this.taskListToolbar);

      current.show();
   }

   public void stop() {
      current = getCurrentForm();
      if (current instanceof Dialog) {
         ((Dialog) current).dispose();
         current = getCurrentForm();
      }
   }

   private Toolbar setToolbar() {
      Toolbar toolbar = new Toolbar();
      current.setToolbar(toolbar);
      toolbar.setTitle("Tasks");

      Button addButton = new Button();
      addButton.addActionListener(e -> new TaskEditor(TaskEditor.TITLE_CREATE));

      try {
         addButton.setIcon(Image.createImage("/addbutton.png").scaled(80, 80));
      } catch (IOException e) {
         e.printStackTrace();
      }

      toolbar.addComponent(BorderLayout.EAST, addButton);
      return toolbar;
   }

   private void setBottomTabs() {
      FontImage taskIcon = FontImage.createMaterial(FontImage.MATERIAL_ALARM,
              "Label", 6);
      FontImage summaryIcon =
              FontImage.createMaterial(FontImage.MATERIAL_ASSESSMENT,
                      "Label", 6);

      Tabs tabs = new Tabs();

      current.add(BorderLayout.CENTER, tabs);
      tabs.addTab("Tasks", taskIcon, new TaskList(this.taskListToolbar));
      tabs.addTab("Summary", summaryIcon, new Summary());
      tabs.setSwipeActivated(false); // Disable the swipe to prevent competition with the cards

      // adds and removes the search bar based on what tab we're on
      tabs.addSelectionListener((oldTabIndex, newTabIndex) -> {
         if (newTabIndex == 0) {
            System.out.println("tab index 0, taskList tab");
            this.current.setToolbar(this.taskListToolbar);
//            TaskList.addSearch();
//            this.current.revalidate();
//            System.out.println("added search");
         } else {
            System.out.println("tab index 1, summary tab");
            this.current.setToolbar(this.summaryToolbar);
//            this.current.revalidate();
//            System.out.println("removed search");
         }
      });
   }

}