package org.ecs160.a2;

import static com.codename1.ui.CN.*;

import com.codename1.ui.*;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;


import org.ecs160.a2.ui.AddNewTask;

import org.ecs160.a2.models.Task;

import org.ecs160.a2.ui.Summary;
import org.ecs160.a2.ui.TaskList;
import org.ecs160.a2.utils.Database;

import java.io.IOException;
import java.lang.Object;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class AppMain {

   private Form current;
   private Resources theme;
   private int x = 4;

   public void init(Object context) {
      // use two network threads instead of one
      updateNetworkThreadCount(2);

      theme = UIManager.initFirstTheme("/theme");

      // Enable Toolbar on all Forms by default
      Toolbar.setGlobalToolbar(true);

      // Pro only feature
      Log.bindCrashProtection(true);

      addNetworkErrorListener(err -> {
         // prevent the event from propagating
         err.consume();
         if (err.getError() != null) {
            Log.e(err.getError());
         }
         Log.sendLogAsync();
         Dialog.show("Connection Error",
                 "There was a networking error in the connection to " +
                         err.getConnectionRequest().getUrl(), "OK",
                 null);
      });

      Database.init();
   }

   public void start() {
      if (current != null) {
         current.show();
         return;
      }

      current = new Form("Task Management App", new BorderLayout());

      for (int i = 0; i < 4; i++) {
         log("Adding initial tasks: Task " + i);
         Task task = new Task("Task Number " + i);
         if (i % 2 == 0) {
            task.start();
         }
         Database.write(Task.OBJECT_ID, task);
      }

      setToolbar();
      setBottomTabs();

      current.show();
   }

   public void stop() {
      current = getCurrentForm();
      if (current instanceof Dialog) {
         ((Dialog) current).dispose();
         current = getCurrentForm();
      }
   }

   public void destroy() {
   }

   private void setToolbar() {
      Toolbar toolbar = new Toolbar();
      current.setToolbar(toolbar);
      toolbar.setTitle("Tasks");

      Button addTaskButton = new Button();
      addTaskButton.addActionListener(e->new AddNewTask().getTaskDialog());

      try {
         addTaskButton.setIcon(Image.createImage("/addbutton.png").scaled(80,80));
      } catch (IOException e) {
         e.printStackTrace();
      }

      toolbar.addComponent(BorderLayout.EAST, addTaskButton);
   }

   private void setBottomTabs() {
      FontImage taskIcon = FontImage.createMaterial(FontImage.MATERIAL_ALARM,
              "Label", 6);
      FontImage summaryIcon =
              FontImage.createMaterial(FontImage.MATERIAL_ASSESSMENT,
              "Label", 6);

      Tabs tabs = new Tabs();
      TaskList taskList = new TaskList();
//      taskList.getListContainer().addPullToRefresh(() -> {
//         for (int i = 0; i < 4; i++) {
//            log("Adding tasks: Task " + (x + i));
//            Task task = new Task("Task Number " + (i + x));
//            if (i % 2 == 0) {
//               task.start();
//            }
//            Database.write(Task.OBJECT_ID, task);
//         }
//         taskList.get();
//         x += 4;
//      });

      current.add(BorderLayout.CENTER, tabs);
      tabs.addTab("Tasks", taskIcon, taskList.get());
      tabs.addTab("Summary", summaryIcon, new Summary().get());
      tabs.setSwipeActivated(false); // Disable the swipe to prevent competition with the cards
   }

   private void showNewTaskForm() {
      log("New Task Form.");
   }
}
